DROP TABLE IF EXISTS users, guest, room, service, residence, purchase, guest_history;

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50)  NOT NULL,
    password VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS guest
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    surname  VARCHAR(50) NOT NULL,
    age      INT         NOT NULL,
    passport VARCHAR(20) NOT NULL,
    phone    VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS room
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state VARCHAR(20) NOT NULL,
    size  INT         NOT NULL,
    price INT         NOT NULL,
    star  INT         NOT NULL
);

CREATE TABLE IF NOT EXISTS service
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(50)          NOT NULL,
    price     INT                  NOT NULL,
    category  VARCHAR(20)          NOT NULL,
    available BOOLEAN default true NOT NULL
);

CREATE TABLE IF NOT EXISTS residence
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id      BIGINT,
    room_id       BIGINT,
    date_checkin  DATE,
    date_checkout DATE,
    CONSTRAINT FK_residence_guest FOREIGN KEY (guest_id) REFERENCES guest (id) ON DELETE CASCADE,
    CONSTRAINT FK_residence_room FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS purchase
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id          BIGINT,
    service_id        BIGINT,
    date_start_rental DATE         NOT NULL,
    date_end_rental   DATE         NOT NULL,
    CONSTRAINT FK_purchase_guest FOREIGN KEY (guest_id) REFERENCES guest (id) ON DELETE CASCADE,
    CONSTRAINT FK_purchase_service FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS guest_history
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id  BIGINT,
    guest_id BIGINT,
    CONSTRAINT FK_room_history_room FOREIGN KEY (room_id) REFERENCES room (id),
    CONSTRAINT FK_guest_history_room FOREIGN KEY (guest_id) REFERENCES guest (id)
);
-- Вставка данных в таблицу Room
INSERT INTO room (state, size, price, star)
VALUES ('FREE', 1, 2000, 3);
INSERT INTO room (state, size, price, star)
VALUES ('FREE', 2, 5000, 4);
INSERT INTO room (state, size, price, star)
VALUES ('FREE', 3, 10000, 5);

-- Вставка данных в таблицу Service
INSERT INTO service (title, price, category)
VALUES ('Халат', 50, 'BATHROOM_ACCESSORIES');
INSERT INTO service (title, price, category)
VALUES ('Breakfast', 20, 'FOOD');
INSERT INTO service (title, price, category)
VALUES ('Утюг', 30, 'TECHNIC');